package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BinhLuan generated by hbm2java
 */
public class BinhLuan  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
     private ThanhVien thanhVien;
     private SanPham sanPham;
     private Date ngayDang;
     private String email;
     private String noiDung;
     private Integer tinhTrang;

    public BinhLuan() {
    }

	
    public BinhLuan(int id) {
        this.id = id;
    }
    public BinhLuan(int id, ThanhVien thanhVien, SanPham sanPham, Date ngayDang, String email, String noiDung, Integer tinhTrang) {
       this.id = id;
       this.thanhVien = thanhVien;
       this.sanPham = sanPham;
       this.ngayDang = ngayDang;
       this.email = email;
       this.noiDung = noiDung;
       this.tinhTrang = tinhTrang;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ThanhVien getThanhVien() {
        return this.thanhVien;
    }
    
    public void setThanhVien(ThanhVien thanhVien) {
        this.thanhVien = thanhVien;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public Date getNgayDang() {
        return this.ngayDang;
    }
    
    public void setNgayDang(Date ngayDang) {
        this.ngayDang = ngayDang;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


