package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GioHang generated by hbm2java
 */
public class GioHang  implements java.io.Serializable {


     private int id;
     private ThanhVien thanhVien;
     private Date ngayCapNhat;
     private Integer tongSoSanPham;
     private Integer soSanPhamDaThanhToan;
     private Integer soSanPhamChuaThanhToan;
     private Integer tinhTrang;
     private Set chiTietGioHangs = new HashSet(0);

    public GioHang() {
    }

	
    public GioHang(int id) {
        this.id = id;
    }
    public GioHang(int id, ThanhVien thanhVien, Date ngayCapNhat, Integer tongSoSanPham, Integer soSanPhamDaThanhToan, Integer soSanPhamChuaThanhToan, Integer tinhTrang, Set chiTietGioHangs) {
       this.id = id;
       this.thanhVien = thanhVien;
       this.ngayCapNhat = ngayCapNhat;
       this.tongSoSanPham = tongSoSanPham;
       this.soSanPhamDaThanhToan = soSanPhamDaThanhToan;
       this.soSanPhamChuaThanhToan = soSanPhamChuaThanhToan;
       this.tinhTrang = tinhTrang;
       this.chiTietGioHangs = chiTietGioHangs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ThanhVien getThanhVien() {
        return this.thanhVien;
    }
    
    public void setThanhVien(ThanhVien thanhVien) {
        this.thanhVien = thanhVien;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public Integer getTongSoSanPham() {
        return this.tongSoSanPham;
    }
    
    public void setTongSoSanPham(Integer tongSoSanPham) {
        this.tongSoSanPham = tongSoSanPham;
    }
    public Integer getSoSanPhamDaThanhToan() {
        return this.soSanPhamDaThanhToan;
    }
    
    public void setSoSanPhamDaThanhToan(Integer soSanPhamDaThanhToan) {
        this.soSanPhamDaThanhToan = soSanPhamDaThanhToan;
    }
    public Integer getSoSanPhamChuaThanhToan() {
        return this.soSanPhamChuaThanhToan;
    }
    
    public void setSoSanPhamChuaThanhToan(Integer soSanPhamChuaThanhToan) {
        this.soSanPhamChuaThanhToan = soSanPhamChuaThanhToan;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getChiTietGioHangs() {
        return this.chiTietGioHangs;
    }
    
    public void setChiTietGioHangs(Set chiTietGioHangs) {
        this.chiTietGioHangs = chiTietGioHangs;
    }




}


