package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HinhAnhThanhVien generated by hbm2java
 */
public class HinhAnhThanhVien  implements java.io.Serializable {


     private int id;
     private ThanhVien thanhVien;
     private Integer tinhTrang;
     private Date ngayCapNhat;
     private String duongDan;

    public HinhAnhThanhVien() {
    }

	
    public HinhAnhThanhVien(int id) {
        this.id = id;
    }
    public HinhAnhThanhVien(int id, ThanhVien thanhVien, Integer tinhTrang, Date ngayCapNhat, String duongDan) {
       this.id = id;
       this.thanhVien = thanhVien;
       this.tinhTrang = tinhTrang;
       this.ngayCapNhat = ngayCapNhat;
       this.duongDan = duongDan;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ThanhVien getThanhVien() {
        return this.thanhVien;
    }
    
    public void setThanhVien(ThanhVien thanhVien) {
        this.thanhVien = thanhVien;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public String getDuongDan() {
        return this.duongDan;
    }
    
    public void setDuongDan(String duongDan) {
        this.duongDan = duongDan;
    }




}


