package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HinhAnhSanPham generated by hbm2java
 */
public class HinhAnhSanPham  implements java.io.Serializable {


     private int id;
     private SanPham sanPham;
     private Integer tinhTrang;
     private Date ngayCapNhat;
     private String duongDan;

    public HinhAnhSanPham() {
    }

	
    public HinhAnhSanPham(int id) {
        this.id = id;
    }
    public HinhAnhSanPham(int id, SanPham sanPham, Integer tinhTrang, Date ngayCapNhat, String duongDan) {
       this.id = id;
       this.sanPham = sanPham;
       this.tinhTrang = tinhTrang;
       this.ngayCapNhat = ngayCapNhat;
       this.duongDan = duongDan;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public String getDuongDan() {
        return this.duongDan;
    }
    
    public void setDuongDan(String duongDan) {
        this.duongDan = duongDan;
    }




}


