package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhaSanXuat generated by hbm2java
 */
public class NhaSanXuat  implements java.io.Serializable {


     private int id;
     private QuocGia quocGia;
     private String tenNhaSanXuat;
     private String diaChi;
     private String email;
     private String soDienThoai;
     private Integer tinhTrang;
     private Date ngayCapNhat;
     private Set sanPhams = new HashSet(0);

    public NhaSanXuat() {
    }

	
    public NhaSanXuat(int id) {
        this.id = id;
    }
    public NhaSanXuat(int id, QuocGia quocGia, String tenNhaSanXuat, String diaChi, String email, String soDienThoai, Integer tinhTrang, Date ngayCapNhat, Set sanPhams) {
       this.id = id;
       this.quocGia = quocGia;
       this.tenNhaSanXuat = tenNhaSanXuat;
       this.diaChi = diaChi;
       this.email = email;
       this.soDienThoai = soDienThoai;
       this.tinhTrang = tinhTrang;
       this.ngayCapNhat = ngayCapNhat;
       this.sanPhams = sanPhams;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public QuocGia getQuocGia() {
        return this.quocGia;
    }
    
    public void setQuocGia(QuocGia quocGia) {
        this.quocGia = quocGia;
    }
    public String getTenNhaSanXuat() {
        return this.tenNhaSanXuat;
    }
    
    public void setTenNhaSanXuat(String tenNhaSanXuat) {
        this.tenNhaSanXuat = tenNhaSanXuat;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public Set getSanPhams() {
        return this.sanPhams;
    }
    
    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }




}


