package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * QuocGia generated by hbm2java
 */
public class QuocGia  implements java.io.Serializable {


     private int id;
     private String tenQuocGia;
     private Set nhaSanXuats = new HashSet(0);

    public QuocGia() {
    }

	
    public QuocGia(int id) {
        this.id = id;
    }
    public QuocGia(int id, String tenQuocGia, Set nhaSanXuats) {
       this.id = id;
       this.tenQuocGia = tenQuocGia;
       this.nhaSanXuats = nhaSanXuats;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTenQuocGia() {
        return this.tenQuocGia;
    }
    
    public void setTenQuocGia(String tenQuocGia) {
        this.tenQuocGia = tenQuocGia;
    }
    public Set getNhaSanXuats() {
        return this.nhaSanXuats;
    }
    
    public void setNhaSanXuats(Set nhaSanXuats) {
        this.nhaSanXuats = nhaSanXuats;
    }




}


