package pojos;
// Generated Oct 21, 2012 10:34:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TuKhoaSanPham generated by hbm2java
 */
@SuppressWarnings("serial")
public class TuKhoaSanPham  implements java.io.Serializable {


     private int id;
     private SanPham sanPham;
     private String keyWord;
     private Date ngayCapNhat;

    public TuKhoaSanPham() {
    }

	
    public TuKhoaSanPham(int id) {
        this.id = id;
    }
    public TuKhoaSanPham(int id, SanPham sanPham, String keyWord, Date ngayCapNhat) {
       this.id = id;
       this.sanPham = sanPham;
       this.keyWord = keyWord;
       this.ngayCapNhat = ngayCapNhat;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public String getKeyWord() {
        return this.keyWord;
    }
    
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }




}


